name: Export

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

env:
  GameName: Test2dPuzzleGame
  BuildVersion: "0.${{ github.run_number}}.0"

jobs:
  build-export:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Godot
        run: |
          Invoke-WebRequest "https://github.com/godotengine/godot-builds/releases/download/4.4.1-stable/Godot_v4.4.1-stable_win64.exe.zip" -OutFile godot.zip
          Expand-Archive .\godot.zip
          & .\godot\Godot_v4.4.1-stable_win64_console.exe --version
          
          Invoke-WebRequest "https://github.com/godotengine/godot-builds/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz" -OutFile templates.zip
          Expand-Archive .\templates.zip C:/Users/runneradmin/AppData/Roaming/Godot/export_templates/
          Rename-Item C:/Users/runneradmin/AppData/Roaming/Godot/export_templates/templates 4.4.1.stable
          ls -r C:/Users/runneradmin/AppData/Roaming/Godot/export_templates

      - name: Build Web
        run: |
          mkdir .\build\web
          & .\godot\Godot_v4.4.1-stable_win64_console.exe --headless --verbose --export-release "Web" .\build\web\index.html

      - name: Upload Web for github pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: ${{ env.GameName }}-Web
          path: build/web

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ env.GameName }}-Web